package bph.entities.utk;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lebah.template.UID;
import portal.module.entity.Users;
import bph.entities.kew.KewJenisBayaran;
import bph.entities.kod.KodHasil;

@Entity
@Table(name = "utk_akaun")
public class UtkAkaun {

	@Id
	@Column(name = "id")
	private String id;
	
	@ManyToOne
	@JoinColumn(name = "id_kesalahan")
	private UtkKesalahan kesalahan;
	
	/**Generated by stakeholder*/
	@ManyToOne
	@JoinColumn(name = "id_kod_hasil")
	private KodHasil kodHasil;
	
	/**Generated by stakeholder*/
	@Column(name = "flag_bayaran")
	private String flagBayaran; /* SEWA; DEPOSIT*/
	
	/**Generated by stakeholder*/
	@Column(name = "no_invois")
	private String noInvois;
	
	/**Generated by stakeholder*/
	@Column(name = "no_rujukan")
	private String noRujukan;
	
	/**Jenis Bayaran (kod modul)*/
	@ManyToOne
	@JoinColumn(name = "id_jenis_bayaran")
	private KewJenisBayaran jenisBayaran;
	
	/**Generated by stakeholder*/
	@Column(name = "keterangan_bayaran")
	private String keteranganBayaran;
	
	/**Generated by stakeholder*/
	@Column(name = "debit")
	private Double debit = 0d;
	
	@Column(name = "kredit")
	private Double kredit = 0d;
	
	@Column(name = "flag_bayar")
	private String flagBayar = "T"; // Y : TELAH BAYAR ; T : BELUM BAYAR ; BTL : BATAL
	
	@Column(name = "flag_queue")
	private String flagQueue = "T"; // Y: IN QUEUE ; T : NO
	
	/**Auditrail*/
	@ManyToOne
	@JoinColumn(name = "id_pendaftar")
	private Users userPendaftar;

	@ManyToOne
	@JoinColumn(name = "id_kemaskini")
	private Users userKemaskini;

	@Temporal(TemporalType.DATE)
	@Column(name = "tarikh_daftar")
	private Date tarikhDaftar = new Date();

	@Temporal(TemporalType.DATE)
	@Column(name = "tarikh_kemaskini")
	private Date tarikhKemaskini;
	
	
	public UtkAkaun() {
		setId(UID.getUID());
	}
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public KodHasil getKodHasil() {
		return kodHasil;
	}

	public void setKodHasil(KodHasil kodHasil) {
		this.kodHasil = kodHasil;
	}

	public String getNoInvois() {
		return noInvois;
	}

	public void setNoInvois(String noInvois) {
		this.noInvois = noInvois;
	}

	public String getNoRujukan() {
		return noRujukan;
	}

	public void setNoRujukan(String noRujukan) {
		this.noRujukan = noRujukan;
	}

	public KewJenisBayaran getJenisBayaran() {
		return jenisBayaran;
	}

	public void setJenisBayaran(KewJenisBayaran jenisBayaran) {
		this.jenisBayaran = jenisBayaran;
	}

	public String getKeteranganBayaran() {
		return keteranganBayaran;
	}

	public void setKeteranganBayaran(String keteranganBayaran) {
		this.keteranganBayaran = keteranganBayaran;
	}

	public Double getDebit() {
		return debit;
	}

	public void setDebit(Double debit) {
		this.debit = debit;
	}

	public Double getKredit() {
		return kredit;
	}

	public void setKredit(Double kredit) {
		this.kredit = kredit;
	}

	public String getFlagBayaran() {
		return flagBayaran;
	}

	public void setFlagBayaran(String flagBayaran) {
		this.flagBayaran = flagBayaran;
	}

	public Users getUserPendaftar() {
		return userPendaftar;
	}

	public void setUserPendaftar(Users userPendaftar) {
		this.userPendaftar = userPendaftar;
	}

	public Users getUserKemaskini() {
		return userKemaskini;
	}

	public void setUserKemaskini(Users userKemaskini) {
		this.userKemaskini = userKemaskini;
	}

	public Date getTarikhDaftar() {
		return tarikhDaftar;
	}

	public void setTarikhDaftar(Date tarikhDaftar) {
		this.tarikhDaftar = tarikhDaftar;
	}

	public Date getTarikhKemaskini() {
		return tarikhKemaskini;
	}

	public void setTarikhKemaskini(Date tarikhKemaskini) {
		this.tarikhKemaskini = tarikhKemaskini;
	}
	
	public String getFlagQueue() {
		return flagQueue;
	}

	public void setFlagQueue(String flagQueue) {
		this.flagQueue = flagQueue;
	}

	public String getFlagBayar() {
		return flagBayar;
	}

	public void setFlagBayar(String flagBayar) {
		this.flagBayar = flagBayar;
	}

	public Double bakiBayaran(){
		Double baki = 0d;
		if(this.debit!=null && this.kredit!=null){
			baki = this.debit - this.kredit;
		}
		return baki;
	}

	public UtkKesalahan getKesalahan() {
		return kesalahan;
	}

	public void setKesalahan(UtkKesalahan kesalahan) {
		this.kesalahan = kesalahan;
	}
	
}
